### PR TITLE
Changes to work alongside Swift.

### PR DESCRIPTION
**Pull request by richrad**
Changed a couple C++ bits to straight C so that this code can be used in a Swift project:
- Changed `cells` to a C array.
- Used `free(cells)` instead of `delete cells`.

### CODE REVIEW

**Comment by pixelogik** [comment]
Hey there, cool thing! Thanks a lot. Will check it out asap. I actually started to port it to Swift because I only use Swift on projects now, but that won't be finished soon because of workload so this is a great contribution :)

**Comment by richrad** [comment]
Thanks! Just thinking about doing a straight Swift port makes my head hurt – I spent a couple hours wrestling with UnsafeMutablePointers/CGBitmapContextCreate in Swift and made very little progress. If you get it working I'd love to see the code!

**Comment by pixelogik** [comment]
Well I've come this far, but I don't know if that does what it should, because I have not finished the port yet and won't in a while (where is the freaking time): 

```
private func rawPixelDataFromImage(image: UIImage) -> ([CUnsignedChar]) {
    // Get cg image and its size
    let cgImage = image.CGImage
    let width = CGImageGetWidth(cgImage)
    let height = CGImageGetHeight(cgImage)

    // Create the color space
    let colorSpace = CGColorSpaceCreateDeviceRGB()

    // Allocate storage for the pixel data
    let rawData = [CUnsignedChar](count: Int(width * height * 4), repeatedValue: 0)

    // Set some metrics
    let bytesPerPixel = 4
    let bytesPerRow = UInt(bytesPerPixel * Int(width))
    let bitsPerComponent = UInt(8)

    // Create context using the storage
    let bitmapInfo = CGBitmapInfo(CGImageAlphaInfo.PremultipliedLast.rawValue | CGBitmapInfo.ByteOrder32Big.rawValue)
    let context = CGBitmapContextCreate(UnsafeMutablePointer<Void>(rawData), width, height, bitsPerComponent, bytesPerRow, colorSpace, bitmapInfo)

    // Draw the image into the storage
    CGContextDrawImage(context, CGRectMake(0, 0, CGFloat(width), CGFloat(height)), cgImage)

    // Return pixel data
    return rawData
}
```

**Comment by pixelogik** [comment]
But things like the CGContext you create manually right? The one who allocates it, is responsible. In this case the array is implicitly allocated by Objective-C and thus also implicitly freed. If this was not the case you would need to free all member variables also. This would be essentially the same as the following, which of course does not compute ;) 

```
@interface CCColorCube () {
    int bla;
}

- (void)dealloc { 
    free(bla);
}
```

**Pull request merged**
